name: TechTrends - Docker package
on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-techtrends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            angfraser/techtrends:latest
            angfraser/techtrends:${{ github.sha }}
